### ISSUE TITLE
Fix pin logic

### ISSUE THREAD

**Issue by tweettypography** [deck-monsters/deck-monsters#135]

**Comment by cormacmccarthy** [comment]
related to #131 and #132 

I think the biggest thing that needs addressed at this point is lowering the freedomThreshold each round. I think a good target would be to make sure they are free after 2~3 rounds.

Right now freedom threshold is `Math.min(player.ac, 10) + this.freedomThresholdModifier;`

I think simply tracking how many rounds they are pinned and then doing something like this would work:

`Math.min(player.ac, 10) + this.freedomThresholdModifier - (roundsPinned * 3);`

**Comment by tweettypography** [comment]
I think we can also remove the `Math.min` and just use the player's AC again now that we allow normal modifiers to apply and have that reduction per round
