### ISSUE TITLE
NPC Ring

### ISSUE THREAD

**Issue by cormacmccarthy** [deck-monsters/deck-monsters#18]
Rename the "ring" class to "encounter" and make a new "ring" class that inherits from it

Give the game a second ring, one that automatically populates an NPC for you based on your XP. Then we could set that up to correspond to a different room in Slack and you'd be able to send your monster into battle against that at any time (sort of a form of grinding...) even if a player wasn't around

**Comment by tweettypography** [comment]
A version of this has been implemented.
