### ISSUE TITLE
Nerf Camo Vest & Faceswap

### ISSUE THREAD

**Issue by cormacmccarthy** [deck-monsters/deck-monsters#184]
Instead of 100% success rate on hiding and reflect the attack:

1d20 + int bonus vs INT to see through the faceswap & camo vest

If fails, and if there are other opponents, hits a random other opponent instead.

Faceswap and camo can not hide you from AOE attacks (eg. Blast).

Camo vest needs to only last 2 turns no matter what.

Faceswap should only be applicable once, if you already have a faceswap in play, you just lose it (they shouldn't stack).

**Comment by tweettypography** [comment]
There's no saving throw for faceswap but this actually feels pretty balanced now so I'm closing
