### ISSUE TITLE
Horn Gore crit fail error

### ISSUE THREAD

**Issue by cormacmccarthy** [deck-monsters/deck-monsters#197]
![image](https://user-images.githubusercontent.com/8006971/35065444-4d338600-fb9b-11e7-8097-b719d08cd14c.png)

![image](https://user-images.githubusercontent.com/8006971/35065387-23f09508-fb9b-11e7-9ca5-78c97a66164e.png)

**Comment by tweettypography** [comment]
I believe this is fixed now
