### ISSUE TITLE
Blast should hit invisible players

### ISSUE THREAD

**Issue by cormacmccarthy** [deck-monsters/deck-monsters#239]
https://www.dropbox.com/s/9fj9baog5v85r1c/Screenshot%202018-01-29%2006.42.28.png?dl=0
🐛

**Comment by tweettypography** [comment]
Yeah this used to work - I'm not sure what the issue was. Maybe the fact that it was part of pick pocket / random?

**Comment by tweettypography** [comment]
This definitely works, and random / pick pocket are supported now as well.
