### ISSUE TITLE
add some sort of backup system to the game

### ISSUE THREAD

**Issue by cormacmccarthy** [deck-monsters/deck-monsters#34]
especially if we envision people playing it for a long time and getting attached to their character / items. Right now it's all in Redis which means it would be lost if the server ever lost power. Also a rogue update or some other issue could cause it to be lost or corrupted.

**Comment by tweettypography** [comment]
Fixed - backs up to AWS now

**Comment by tweettypography** [comment]
(after we already lost everything...)
