### ISSUE TITLE
XP should be relative based on level

### ISSUE THREAD

**Issue by cormacmccarthy** [deck-monsters/deck-monsters#87]
Something like:

winner level > loser level = XP-(winner level-loser level)
winner level == loser level = XP
winner level < loser level = XP+(loser level-winner level)

**Comment by RodEsp** [comment]
How about `-0.3 * x=log(y)` where `x` is the difference between the levels of the monsters?

**Comment by RodEsp** [comment]
![image](https://user-images.githubusercontent.com/1084688/33908430-5e946556-df56-11e7-99a0-d7b72796aa86.png)

**Comment by tweettypography** [comment]
But first is the adjusted XP gain.


Eric Willhoit [9:28 AM] 
that should go both ways, if you defeat a monster that is a higher level than you, you should get more xp


Rodrigo Espinosa de los Monteros 
[9:29 AM] 
You think so?


Eric Willhoit [9:29 AM] 
yea, if i happen to defeat a level 3 with a level 1.. i think that is worth more



David Brainer
[9:29 AM] 
Ah yeh, that's a good one. My thinking is: when you are a "winner" of match you get a static bonus, then you get a bonus for any monster you personally killed based on their xp (edited)


Rodrigo Espinosa de los Monteros [9:29 AM] 
What I was going to do is take the base value of 10 XP per win and multiply it times the value of a logarithmic function based on the difference between the monster's level.


[9:29] 
https://github.com/deck-monsters/deck-monsters/issues/87


David Brainer [9:29 AM] 
If they are lower level than you it's a very small bonus, and it grows as they get stronger than you


Rodrigo Espinosa de los Monteros 
[9:30 AM] 
I can just use negative differences too to make it higher. (edited)


David Brainer [9:31 AM] 
Baseline could be something like 5 xp per win + 5 xp to have killed a monster of your own level - so you'd still make exactly 10 xp for a 1 v 1 battle where your opponent is the same level as you


[9:32] 
And then based on your function the number on the right would grow or shrink as needed


Rodrigo Espinosa de los Monteros [9:33 AM] 
Hmm... how would that work on multi-monster battles?


[9:33] 
Just take the lowest/highest level monster and calculate against that for the winner?


David Brainer [9:33 AM] 
No, from above: "then you get a bonus for any monster you personally killed based on their xp" ^


[9:34] 
So in a multi-monster battle where you killed everyone and won you might get 5xp base + 5xp + 5xp + 5xp

Rodrigo Espinosa de los Monteros [9:34 AM] 
Oh, sorry didn't see that.

David Brainer
[9:34 AM] 
In a multi-monster battle where you won but only killed one of the monsters you get 5xp base + 5xp and someone else gets the other monster bonuses

[9:35] 
So the monster bonus can be calculated based on the distance between you and the other monster while the win bonus is constant

Rodrigo Espinosa de los Monteros 
[9:35 AM] 
Shit, that's going to be quite the rewrite. It looks to me like this only supports 1 winner per battle right now.

[9:36] 
Actually... there are events for dying for each monster... hmm... maybe it's not so bad.

David Brainer
[9:36 AM] 
I'm not sure it saves who kills who right now but the monsters themselves know (and events are triggered) so it'd be easy to manage I think

Rodrigo Espinosa de los Monteros [9:36 AM] 
Right.
